using System.Collections.Generic;

namespace iSukces.Geo;

public sealed partial class SurveyorRegistryObject
{
    public SurveyorRegistryObject(string code, string group, string description)
    {
        Code        = code.Trim().ToUpper();
        Group       = group.Trim();
        Description = description.Trim();
    }

    public string Code        { get; }
    public string Group       { get; }
    public string Description { get; }

    public static IReadOnlyList<SurveyorRegistryObject> KnownObjects { get; } = GetKnownCodes();
}

// -----===== autogenerated code =====-----
// ReSharper disable All
partial class SurveyorRegistryObject
{
    // Sporządzone na podstawie https://sip.lex.pl/akty-prawne/dzu-dziennik-ustaw/baza-danych-obiektow-topograficznych-oraz-mapa-zasadnicza-19135412
    private static System.Collections.Generic.IReadOnlyList<SurveyorRegistryObject> GetKnownCodes()
    {
        return new []
        {
            new SurveyorRegistryObject("SUWP", "Sieć wodociągowa", "Przewód wodociągowy"),
            new SurveyorRegistryObject("SUWU", "Sieć wodociągowa", "Wodociągowe urządzenie techniczne"),
            new SurveyorRegistryObject("SUWW", "Sieć wodociągowa", "Zasuwa lub zawór"),
            new SurveyorRegistryObject("SUWR", "Sieć wodociągowa", "Hydrofornia"),
            new SurveyorRegistryObject("SUWH", "Sieć wodociągowa", "Hydrant"),
            new SurveyorRegistryObject("SUWD", "Sieć wodociągowa", "Zdrój uliczny"),
            new SurveyorRegistryObject("SUWS", "Sieć wodociągowa", "Studnia zwykła"),
            new SurveyorRegistryObject("SU WG", "Sieć wodociągowa", "Studnia głębinowa"),
            new SurveyorRegistryObject("SUKP", "Sieć kanalizacyjna", "Przewód kanalizacyjny"),
            new SurveyorRegistryObject("SUKU", "Sieć kanalizacyjna", "Kanalizacyjne urządzenie techniczne"),
            new SurveyorRegistryObject("SUKW", "Sieć kanalizacyjna", "Zasuwa lub zawór"),
            new SurveyorRegistryObject("SUKS", "Sieć kanalizacyjna", "Studnia kanalizacyjna"),
            new SurveyorRegistryObject("SUKK", "Sieć kanalizacyjna", "Kratka ściekowa"),
            new SurveyorRegistryObject("SUKL", "Sieć kanalizacyjna", "Odwodnienie liniowe"),
            new SurveyorRegistryObject("SUKM", "Sieć kanalizacyjna", "Osadnik, szambo"),
            new SurveyorRegistryObject("SUKD", "Sieć kanalizacyjna", "Przydomowa oczyszczalnia ścieków"),
            new SurveyorRegistryObject("SUKE", "Sieć kanalizacyjna", "Wylot kanału"),
            new SurveyorRegistryObject("SUKN", "Sieć kanalizacyjna", "Przepompownia"),
            new SurveyorRegistryObject("SUEP", "Sieć elektroenergetyczna", "Przewód elektroenergetyczny"),
            new SurveyorRegistryObject("SUEU", "Sieć elektroenergetyczna", "Elektroenergetyczne urządzenie techniczne"),
            new SurveyorRegistryObject("SUES", "Sieć elektroenergetyczna", "Szafa elektroenergetyczna lub kontener"),
            new SurveyorRegistryObject("SUET", "Sieć elektroenergetyczna", "Stacja transformatorowa"),
            new SurveyorRegistryObject("SUEO", "Sieć elektroenergetyczna", "Latarnia"),
            new SurveyorRegistryObject("SUEM", "Sieć elektroenergetyczna", "Maszt oświetleniowy"),
            new SurveyorRegistryObject("SUEA", "Sieć elektroenergetyczna", "Turbina wiatrowa"),
            new SurveyorRegistryObject("SUEL", "Sieć elektroenergetyczna", "Stacja ładowania pojazdów elektrycznych"),
            new SurveyorRegistryObject("SUGP", "Sieć gazowa", "Przewód gazowy"),
            new SurveyorRegistryObject("SUGU", "Sieć gazowa", "Gazowe urządzenie techniczne"),
            new SurveyorRegistryObject("SUGW", "Sieć gazowa", "Zasuwa lub zawór"),
            new SurveyorRegistryObject("SUGS", "Sieć gazowa", "Szafa gazowa lub kontener"),
            new SurveyorRegistryObject("SUGN", "Sieć gazowa", "Stacja gazowa"),
            new SurveyorRegistryObject("SUGV", "Sieć gazowa", "Zbiornik gazu"),
            new SurveyorRegistryObject("SUCP", "Sieć ciepłownicza", "Przewód ciepłowniczy"),
            new SurveyorRegistryObject("SUCU", "Sieć ciepłownicza", "Ciepłownicze urządzenie techniczne"),
            new SurveyorRegistryObject("SUCW", "Sieć ciepłownicza", "Zasuwa lub zawór"),
            new SurveyorRegistryObject("SUTP", "Sieć telekomunikacyjna", "Przewód telekomunikacyjny"),
            new SurveyorRegistryObject("SUTU", "Sieć telekomunikacyjna", "Telekomunikacyjne urządzenie techniczne"),
            new SurveyorRegistryObject("SUTS", "Sieć telekomunikacyjna", "Szafa telekomunikacyjna lub kontener"),
            new SurveyorRegistryObject("SUTW", "Sieć telekomunikacyjna", "Wieża telekomunikacyjna"),
            new SurveyorRegistryObject("SUTK", "Sieć telekomunikacyjna", "Słupek telekomunikacyjny"),
            new SurveyorRegistryObject("SUSP", "Sieć specjalna", "Przewód specjalny"),
            new SurveyorRegistryObject("SUSU", "Sieć specjalna", "Urządzenie techniczne sieci specjalnej"),
            new SurveyorRegistryObject("SUNP", "Sieć niezidentyfikowana", "Przewód niezidentyfikowany"),
            new SurveyorRegistryObject("SUNU", "Sieć niezidentyfikowana", "Urządzenie techniczne sieci niezidentyfikowanej"),
            new SurveyorRegistryObject("SULL", "Urządzenia towarzyszące liniowe", "Kanał technologiczny"),
            new SurveyorRegistryObject("SULO", "Urządzenia towarzyszące liniowe", "Obudowa ochronna przewodu"),
            new SurveyorRegistryObject("SUPK", "Inne urządzenia towarzyszące", "Komora podziemna"),
            new SurveyorRegistryObject("SUPW", "Inne urządzenia towarzyszące", "Właz do komory lub kanału"),
            new SurveyorRegistryObject("SUPP", "Inne urządzenia towarzyszące", "Słup przewodów napowietrznych"),
            new SurveyorRegistryObject("SUPY", "Inne urządzenia towarzyszące", "Słup trakcyjny"),
            new SurveyorRegistryObject("SUPN", "Inne urządzenia towarzyszące", "Podpora przewodów"),
            new SurveyorRegistryObject("SUPB", "Inne urządzenia towarzyszące", "Budowla podziemna")
        };
    }

}
